### ISSUE TITLE
Should the QEO (or SW fallback) be undocked from Windows?

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/net-offloads#13]
While it may seem premature to bring this up, an undocked QEO could impose some requirements on the NDIS spec:

1. The `NDIS_OFFLOAD` family of OIDs and structs are handled extensively in ndis.sys, so any changes to those structs requires changes to NDIS. If separate OIDs/structs are used, NDIS can treat them as fully opaque, allowing QEO to be updated without churning/servicing NDIS.
2. Require future-proofing the OOB fields? Would the OOB need to be a pointer to an opaque QEO struct rather than having the OOB contain the struct itself?

Even if QEO is not undocked at first, specifying API contracts to allow future undocking gives us flexibility to undock in the future.

**Comment by mskhot** [comment]
> cc @mskhot for perspective on the vmswitch side
> 
What we have run into with RSC in vswitch is that there are L3/L4 rules about how the different TCP flags can affect whether you should coalesce packets.  Therefore, what the vswitch'd like to share with TCP is any L3/L4 logic & policies such as flow tracking, connection lifetime, what's offloadable and what's not.  That way, there's a single SME source, and a single place to update the code, as bugs are found and as these L3/L4 rules evolve over time.

Additionally, as we design this shared library, we should do a mental exercise on how it'll be used in vswitch, so we can tweak the API of this library as needed.  For example:
- Connection tracking & encryption/decryption may need to be performed on the inner packets, depending on whether they're done before or after encapsulation.
- Will the connections for different VMs be distinguishable from one another?  Would each VM have its own connection table, or will there be something else in the table that'd distinguish connections to different VMs.  These VMs may have the same IP address space on the inner packets.

**Comment by nibanks** [comment]
I'm going to resolve this one, as we've generally decided the answer is "Yes, it will be undocked" but to start, we are targeting XDP-only support for QEO and not socket-based API support. We may provide the functionality at a later time for sockets, and if/when we do it will be undocked.
