### ISSUE TITLE
Should URO aggregate packets with different connection IDs?

### ISSUE THREAD

**Issue by BorisPis** [microsoft/net-offloads#30]
Perhaps I'm missing something, but it seems like only the decryption status is used to aggregate packets. If the NIC performs this aggregation and ignores the connection ID (CID) then packets of different CIDs will be aggregated - is that desirable?

**Comment by nibanks** [comment]
The UDP tuple is also used, as well as everything else normally applicable to URO (such as ECN). You can see MsQuic's receive path (Windows user mode) struct for ancillary data [here](https://github.com/microsoft/msquic/blob/main/src/platform/datapath_winuser.c#L260). We will simply add the decryption status to this.

**Comment by nibanks** [comment]
Though, this brings up a related topic that we've been toying around with already:

**Should we also add HW URO support?**

We've seen issues with NICs treating UDP and TCP traffic differently because TCP HW buffers are 64KB RSC and UDP HW buffers are MTU sized; because they're not decided for coalescing on the receive path. QEO might make this even more important.

**Comment by nibanks** [comment]
> Can't speak for NICs in general, but as QUIC gains popularity, it is reasonable to expect URO to be offloaded. Do you happen to have existing applications that will benefit from this?

Yes. SMB over QUIC should benefit because it routinely has high bandwidth transfers. Beyond that, I expect large file transfers over HTTP to also benefit. Generally, anything that's using at least several hundred-megabit transfers would likely benefit.

**Comment by BorisPis** [comment]
Thanks for the summary, and sorry for commenting on a close issue.

> When doing URO+QEO, you shouldn't aggregate packets with different CIDs because they will use different keys to decrypt

Interesting. I agree that URO+QEO shouldn't aggregate successfully decrypted packets with those that failed decryption, but it seems alright to aggregate QUIC packets with different CIDs belonging to the same 5-tuple that were successfully decrypted, right? because all of them will go to the same application anyway, no?

By the way, I don't see QEO+URO mentioned in the URO spec.

> generally URO aggregation is meant to combine packets with the same metadata, and QEO metadata wouldn't be the same.

IMO, the metadata is "decrypted". Using metadata such is "decrypted using this CID" is possible, but not obvious, and should be discussed further in necessary.

> If just URO (no QEO) is being performed, then the CID can be ignored when decided how to aggregate the packets, which can result in packets with different CIDs (but the same tuple?) being combined.

Yes, that makes sense.
