### ISSUE TITLE
[URO] add support for larger than IP max length agggregation

### ISSUE THREAD

**Issue by BorisPis** [microsoft/net-offloads#59]
The URO spec says:
 > The total length of the Single Coalesced Unit (SCU) must not exceed IP max length.

In Linux, larger than max IP length aggregation has been shown to be beneficial https://lwn.net/Articles/883713/

I recommend that you also consider this. Also, IMO, doing this for IPv4 might be beneficial too, even if somewhat more complicated.

**Comment by anrossi** [comment]
That's an interesting finding!
What happens with the checksum fields? Are they just ignored? Are the length fields just maximum?
