### ISSUE TITLE
As per our understanding Windows does not support System Clock and PHC clock synchronization. But Time Based Packet Transmission has clock synchronization as prerequisite. Any plans on synchronizing the clocks in Windows?

### ISSUE THREAD

**Issue by indrakumarkr** [microsoft/net-offloads#65]
https://github.com/microsoft/quic-offloads/blame/fc6f00badd3567394a59ed8d1267fd0a8764776c/time-based-packet-transmission-offload.md#L26

**Comment by nibanks** [comment]
Closing #64 and #65 because we have updated TPTO to use relative (to `Now()`) time, which eliminates the need for any clock synchronization.
